-- CREATE USER TABLE
CREATE TABLE USERS (
user_id NUMBER(10) NOT NULL,
username VARCHAR2(50) NOT NULL,
email VARCHAR2(254) NOT NULL,
password VARCHAR2(50) NOT NULL,
CONSTRAINT users_pk PRIMARY KEY (user_id),
CONSTRAINT user_unique UNIQUE(username),
CONSTRAINT email_unique UNIQUE(email)
);

-- CREATE TOPIC TABLE
CREATE TABLE TOPIC (
topic_id NUMBER(10) NOT NULL,
title VARCHAR2(60) NOT NULL,
description VARCHAR2(1000) NOT NULL,
CONSTRAINT topic_id PRIMARY KEY (topic_id)
);

-- CREATE POSTS TABLE
CREATE TABLE POST (
post_id NUMBER(10) NOT NULL,
title VARCHAR2(60) NOT NULL,
description VARCHAR2(1000) NOT NULL,
p_date TIMESTAMP(0) NOT NULL,
author VARCHAR2(50) NOT NULL,
topic_id NUMBER(10),
CONSTRAINT pk_post PRIMARY KEY (post_id),
CONSTRAINT fk_topic FOREIGN KEY (topic_id) REFERENCES TOPIC (topic_id)
);

-- CREATE REPLIES TABLE
CREATE TABLE REPLIES (
reply_id NUMBER(10) NOT NULL,
description VARCHAR2(1000) NOT NULL,
r_date TIMESTAMP(0) NOT NULL,
author VARCHAR2(50) NOT NULL,
post_id NUMBER(10) NOT NULL,
reply_to NUMBER(10),
CONSTRAINT pk_reply PRIMARY KEY (reply_id),
CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES POST (post_id),
CONSTRAINT fk_reply FOREIGN KEY (reply_to) REFERENCES REPLIES (reply_id)
);



