-- CREATE USER TABLE
CREATE TABLE USERS (
user_id NUMBER(10) NOT NULL,
username VARCHAR2(50) NOT NULL,
email VARCHAR2(254) NOT NULL,
password VARCHAR2(300) NOT NULL,
CONSTRAINT users_pk PRIMARY KEY (user_id),
CONSTRAINT user_unique UNIQUE(username),
CONSTRAINT email_unique UNIQUE(email)
);

-- CREATE TOPIC TABLE
CREATE TABLE TOPIC (
topic_id NUMBER(10) NOT NULL,
title VARCHAR2(60) NOT NULL,
description VARCHAR2(1000) NOT NULL,
CONSTRAINT topic_id PRIMARY KEY (topic_id)
);

-- CREATE POSTS TABLE
CREATE TABLE POST (
post_id NUMBER(10) NOT NULL,
title VARCHAR2(60) NOT NULL,
description VARCHAR2(1000) NOT NULL,
p_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
author VARCHAR2(50) NOT NULL,
topic_id NUMBER(10),
CONSTRAINT pk_post PRIMARY KEY (post_id),
CONSTRAINT fk_topic FOREIGN KEY (topic_id) REFERENCES TOPIC (topic_id)
);

-- CREATE REPLIES TABLE
CREATE TABLE REPLIES (
reply_id NUMBER(10) NOT NULL,
description VARCHAR2(1000) NOT NULL,
r_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
author VARCHAR2(50) NOT NULL,
post_id NUMBER(10) NOT NULL,
reply_to NUMBER(10),
CONSTRAINT pk_reply PRIMARY KEY (reply_id),
CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES POST (post_id),
CONSTRAINT fk_reply FOREIGN KEY (reply_to) REFERENCES REPLIES (reply_id)
);

-- CREATE SEQUENCE FOR USER TABLE
CREATE SEQUENCE user_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE SEQUENCE FOR USER TABLE
CREATE SEQUENCE topic_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE SEQUENCE FOR POST TABLE
CREATE SEQUENCE post_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE SEQUENCE FOR REPLIES TABLE
CREATE SEQUENCE reply_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE PERMANENT TABLESPACE
CREATE TABLESPACE tbs_perm_01
DATAFILE 'tbs_perm_01.dat'
SIZE 10M
REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

-- CREATE TEMPORARY TABLESPACE
CREATE TEMPORARY TABLESPACE tbs_temp_01
TEMPFILE 'tbs_temp_01.dbf'
SIZE 100M;

-- CREATE UNDO TABLESPACE
CREATE UNDO TABLESPACE tbs_undo_01
DATAFILE 'tbs_undo_01.f'
SIZE 5M
AUTOEXTEND ON
RETENTION GUARANTEE;

-- CREATE USER
CREATE USER spring
IDENTIFIED BY tekmexico123
DEFAULT TABLESPACE tbs_perm_01
TEMPORARY TABLESPACE tbs_temp_01
QUOTA 20M ON tbs_perm_01;

-- CREATE USER ROLE
CREATE ROLE USER_ROLE IDENTIFIED BY user_role123;

-- GRANT PRIVILEGES TO USER ROLE
GRANT CREATE SESSION TO USER_ROLE;
GRANT INSERT, UPDATE, DELETE, SELECT ON USERS TO USER_ROLE;
GRANT INSERT, UPDATE, DELETE, SELECT ON TOPIC TO USER_ROLE;
GRANT INSERT, UPDATE, DELETE, SELECT ON POST TO USER_ROLE;
GRANT INSERT, UPDATE, DELETE, SELECT ON REPLIES TO USER_ROLE;
GRANT SELECT ON user_seq TO USER_ROLE;
GRANT SELECT ON topic_seq TO USER_ROLE;
GRANT SELECT ON post_seq TO USER_ROLE;
GRANT SELECT ON reply_seq TO USER_ROLE;

-- GRANT USER ROLE TO SPRING USER
GRANT USER_ROLE TO spring;
GRANT CREATE SESSION TO spring;

-- USER ROLE AS DEFAULT OF SPRING USER
ALTER USER spring DEFAULT ROLE USER_ROLE;

-- GRANT PRIVILEGES TO SPRING USER
GRANT CREATE SESSION TO spring;
GRANT INSERT, UPDATE, DELETE, SELECT ON USERS TO spring;
GRANT INSERT, UPDATE, DELETE, SELECT ON TOPIC TO spring;
GRANT INSERT, UPDATE, DELETE, SELECT ON POST TO spring;
GRANT INSERT, UPDATE, DELETE, SELECT ON REPLIES TO spring;
GRANT SELECT ON user_seq TO spring;
GRANT SELECT ON topic_seq TO spring;
GRANT SELECT ON post_seq TO spring;
GRANT SELECT ON reply_seq TO spring;







